In [1]:
import numpy as np
# !pip install numpy 

In [3]:
# dir(np)

In [4]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [5]:
type(arr)

numpy.ndarray

In [6]:
len(arr)

5

In [7]:
arr.shape

(5,)

In [8]:
arr.size

5

In [9]:
lst = [[1,2,3] , [2,3,4] , [3,4,5] , [4,5,6]]
m = np.array(lst)
m

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [10]:
m.shape

(4, 3)

In [12]:
print(f"Number of rows is: {m.shape[0]}")
print(f"Number of columns is: {m.shape[1]}")

Number of rows is: 4
Number of columns is: 3


In [13]:
m

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [14]:
m.astype(float)

array([[1., 2., 3.],
       [2., 3., 4.],
       [3., 4., 5.],
       [4., 5., 6.]])

In [21]:
lst = [['1',2,3] , [2,3,4] , [3,4,5] , [4,5,6]]
x = np.array(lst , dtype = "i")
x

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]], dtype=int32)

In [22]:
m

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [23]:
m[0]

array([1, 2, 3])

In [24]:
m[-1]

array([4, 5, 6])

In [25]:
m[0][0]

1

In [26]:
# m[ rows , cols]   m[: , :]
m[0 , 0]

1

In [28]:
m[0:4 , 0:1]

array([[1],
       [2],
       [3],
       [4]])

In [30]:
m[ : , 0:1 ]

array([[1],
       [2],
       [3],
       [4]])

In [38]:
m[: , -1:]

array([[3],
       [4],
       [5],
       [6]])

In [39]:
np.flip(m)

array([[6, 5, 4],
       [5, 4, 3],
       [4, 3, 2],
       [3, 2, 1]])

In [43]:
m[: , : :-1]

array([[3, 2, 1],
       [4, 3, 2],
       [5, 4, 3],
       [6, 5, 4]])

In [55]:
a = np.arange(1 , 101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [57]:
a = np.arange(1 , 101)
data = a.reshape((20,5))
data[: , -1] = [1,0,0,0,0,0,0,0,1,1,1,0,1,1,1,1 ,0,1,1,0]

In [62]:
data[: , -1] = [1,0,0,0,0,0,0,0,1,1,1,0,1,1,1,1 ,0,1,1,0]

In [72]:
data[: , -1:]

array([[1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0]])

In [80]:
def train_test_split(data , per =.5):
    y = data[: , -1:]
    x = data[: ,   :-1]
    num_of_rows = int(len(data)* per) 
    x_train , x_test = x[ :num_of_rows , : ] , x[ num_of_rows: , : ]
    y_train , y_test = y[ :num_of_rows , : ] , y[ num_of_rows: , : ]
    
    return x_train , x_test , y_train , y_test


x_train , x_test , y_train , y_test = train_test_split(data , .6)

In [82]:
x_train.shape

(12, 4)

In [83]:
x_test.shape

(8, 4)

In [84]:
y_train.shape

(12, 1)

In [85]:
y_test.shape

(8, 1)

In [86]:
data

array([[ 1,  2,  3,  4,  1],
       [ 6,  7,  8,  9,  0],
       [11, 12, 13, 14,  0],
       [16, 17, 18, 19,  0],
       [21, 22, 23, 24,  0],
       [26, 27, 28, 29,  0],
       [31, 32, 33, 34,  0],
       [36, 37, 38, 39,  0],
       [41, 42, 43, 44,  1],
       [46, 47, 48, 49,  1],
       [51, 52, 53, 54,  1],
       [56, 57, 58, 59,  0],
       [61, 62, 63, 64,  1],
       [66, 67, 68, 69,  1],
       [71, 72, 73, 74,  1],
       [76, 77, 78, 79,  1],
       [81, 82, 83, 84,  0],
       [86, 87, 88, 89,  1],
       [91, 92, 93, 94,  1],
       [96, 97, 98, 99,  0]])

In [87]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,3,4])
np.concatenate((arr1,arr2))

array([1, 2, 3, 4, 5, 6, 3, 4])

In [88]:
np.hstack((arr1,arr2))

array([1, 2, 3, 4, 5, 6, 3, 4])

In [89]:
np.vstack((arr1,arr2))

array([[1, 2, 3, 4],
       [5, 6, 3, 4]])

In [91]:
m = np.array([[1, 2, 3, 4],[5, 6, 3, 4]])
m

array([[1, 2, 3, 4],
       [5, 6, 3, 4]])

In [92]:
arr1

array([1, 2, 3, 4])

In [94]:
np.vstack((m,arr1))

array([[1, 2, 3, 4],
       [5, 6, 3, 4],
       [1, 2, 3, 4]])

In [95]:
m2 = np.array([[5, 6, 3, 4],[1, 2, 3, 4]])
m2

array([[5, 6, 3, 4],
       [1, 2, 3, 4]])

In [96]:
m

array([[1, 2, 3, 4],
       [5, 6, 3, 4]])

In [97]:
np.hstack((m,m2))

array([[1, 2, 3, 4, 5, 6, 3, 4],
       [5, 6, 3, 4, 1, 2, 3, 4]])

In [99]:
w = np.vstack((m,m2))

In [100]:
w

array([[1, 2, 3, 4],
       [5, 6, 3, 4],
       [5, 6, 3, 4],
       [1, 2, 3, 4]])

In [104]:
# w[w==1]

In [106]:
for i in w:
    for j in i :
        print(j)

1
2
3
4
5
6
3
4
5
6
3
4
1
2
3
4


In [108]:
for i in np.nditer(w):
    print(i)

1
2
3
4
5
6
3
4
5
6
3
4
1
2
3
4


In [116]:
np.array_equal(m , w)

False

In [117]:
m  == m 

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [118]:
m

array([[1, 2, 3, 4],
       [5, 6, 3, 4]])

In [119]:
for i in np.nditer(m):
    print(i)

1
2
3
4
5
6
3
4


In [120]:
m

array([[1, 2, 3, 4],
       [5, 6, 3, 4]])

In [121]:
m[m > 3]

array([4, 5, 6, 4])

In [122]:
m[ m%2==0 ]

array([2, 4, 6, 4])

In [123]:
m[m%2 != 0]

array([1, 3, 5, 3])

In [125]:
np.zeros((3,3) , dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [127]:
np.ones((3,4) , dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [129]:
w = np.zeros((10,10) , dtype = int)
w

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [133]:
w[1:-1 , 1:-1] = 1

In [134]:
w

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [162]:
np.empty((3,3) , dtype = int)

array([[        0,         1,         0],
       [      580,       360,         0],
       [      768,     32760, 544174880]])

In [146]:
np.linspace(1 , 10 , 4)

array([ 1.,  4.,  7., 10.])

In [164]:
m

array([[1, 2, 3, 4],
       [5, 6, 3, 4]])

In [165]:
lst = [1,2,3]
for i , v in enumerate(lst):
    print(i , v)

0 1
1 2
2 3


In [167]:
print(m)
for i , v in np.ndenumerate(m):
    print(i , v )

[[1 2 3 4]
 [5 6 3 4]]
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 3
(1, 3) 4
