In [1]:
# s = 5 #scalar value 
# v = [12,34,56] #vector
# m = [[1,2,3],
#      [1,2,3],
#      [3,4,5]]
# t = [[[1,2,3], [2,3,4]]]

In [2]:
import numpy as np 

In [3]:
np.array([12,34,56])

array([12, 34, 56])

In [6]:
m = np.array([[1,2,3],
          [1,2,3],
         [3,4,5]])
m

array([[1, 2, 3],
       [1, 2, 3],
       [3, 4, 5]])

In [8]:
m[0][0]

1

In [9]:
m[0 , 0]

1

In [10]:
m[: , 0]

array([1, 1, 3])

In [11]:
m[: , 0:1]

array([[1],
       [1],
       [3]])

In [12]:
m[: , -1:]

array([[3],
       [3],
       [5]])

In [13]:
m[ : 2 , : 2]

array([[1, 2],
       [1, 2]])

In [14]:
type(m)

numpy.ndarray

In [15]:
m.reshape((9,1))

array([[1],
       [2],
       [3],
       [1],
       [2],
       [3],
       [3],
       [4],
       [5]])

In [19]:
np.arange(1 , 11).reshape((-1,1))

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [20]:
m

array([[1, 2, 3],
       [1, 2, 3],
       [3, 4, 5]])

In [21]:
m.shape

(3, 3)

In [22]:
s = 2 
s * m 

array([[ 2,  4,  6],
       [ 2,  4,  6],
       [ 6,  8, 10]])

In [23]:
lst = [[1, 2, 3],[1, 2, 3],[3, 4, 5]]

In [24]:
result = []
for i in lst :
    res = []
    for j in i :
        res.append(2 * j )
    result.append(res)

for i in result:
    print(i)

[2, 4, 6]
[2, 4, 6]
[6, 8, 10]


In [25]:
s + m 

array([[3, 4, 5],
       [3, 4, 5],
       [5, 6, 7]])

In [26]:
result = []
for i in lst :
    res = []
    for j in i :
        res.append(2 + j )
    result.append(res)

for i in result:
    print(i)

[3, 4, 5]
[3, 4, 5]
[5, 6, 7]


In [27]:
v = np.array([1,2,3])

In [28]:
v

array([1, 2, 3])

In [29]:
s * v

array([2, 4, 6])

In [30]:
s + v 

array([3, 4, 5])

In [31]:
v

array([1, 2, 3])

In [32]:
m

array([[1, 2, 3],
       [1, 2, 3],
       [3, 4, 5]])

In [33]:
v + m

array([[2, 4, 6],
       [2, 4, 6],
       [4, 6, 8]])

In [34]:
v * m

array([[ 1,  4,  9],
       [ 1,  4,  9],
       [ 3,  8, 15]])

In [38]:
v2 = v.reshape((-1 , 1))
v2

array([[1],
       [2],
       [3]])

In [39]:
m

array([[1, 2, 3],
       [1, 2, 3],
       [3, 4, 5]])

In [40]:
v2 * m

array([[ 1,  2,  3],
       [ 2,  4,  6],
       [ 9, 12, 15]])

In [41]:
v2 + m

array([[2, 3, 4],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
v_1 = np.array([1,2])

In [43]:
v_1

array([1, 2])

In [44]:
m

array([[1, 2, 3],
       [1, 2, 3],
       [3, 4, 5]])

In [47]:
try:
    v_1 * m
except Exception as e :
    print(f"Error is : {e}")

Error is : operands could not be broadcast together with shapes (2,) (3,3) 


In [48]:
# s * m
# s + m 

# v * m 
# v + m 

In [49]:
m 

array([[1, 2, 3],
       [1, 2, 3],
       [3, 4, 5]])

In [54]:
m2 =  np.arange(0 , 9).reshape((3,3))
m2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [55]:
print(m.shape)
print(m2.shape)

(3, 3)
(3, 3)


In [56]:
m + m2 

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 9, 11, 13]])

In [57]:
m * m2

array([[ 0,  2,  6],
       [ 3,  8, 15],
       [18, 28, 40]])

In [59]:
w = m[0:2 , :]
w

array([[1, 2, 3],
       [1, 2, 3]])

In [60]:
w.shape

(2, 3)

In [61]:
m2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [62]:
m2.shape

(3, 3)

In [65]:
# w * m2

In [66]:
m

array([[1, 2, 3],
       [1, 2, 3],
       [3, 4, 5]])

In [67]:
m2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [68]:
# x * y >> (m,m) == (m,m)
# x dot y >> (.w.,n) == (n,.m.)  >> (w,m)
x = np.array([[1,2],[2,3],[4,5]])
x

array([[1, 2],
       [2, 3],
       [4, 5]])

In [69]:
y = np.array([[1,2,3] , [2,3,4]])
y

array([[1, 2, 3],
       [2, 3, 4]])

In [71]:
print(x.shape , y.shape)


(3, 2) (2, 3)


In [72]:
x

array([[1, 2],
       [2, 3],
       [4, 5]])

In [79]:
y  

array([[1, 2, 3],
       [2, 3, 4]])

In [80]:
x.dot(y)  #np.dot(x,y)   # 1 * 1 + 2 * 2  , 1 * 2 + 2 * 3  , 1 * 3 + 2 * 4 

array([[ 5,  8, 11],
       [ 8, 13, 18],
       [14, 23, 32]])

In [76]:
np.dot(x,y)

array([[ 5,  8, 11],
       [ 8, 13, 18],
       [14, 23, 32]])

In [81]:
# x * y 

In [83]:
t = np.array([[1,2,3] , [2,3,4] , [3,4,5]])
t

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [84]:
np.tril(t)

array([[1, 0, 0],
       [2, 3, 0],
       [3, 4, 5]])

In [85]:
np.triu(t)

array([[1, 2, 3],
       [0, 3, 4],
       [0, 0, 5]])

In [86]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [87]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [90]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [91]:
t

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [92]:
np.diag(t)

array([1, 3, 5])

In [93]:
np.diag([1, 3, 5])

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [94]:
np.diag(np.diag(t))

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [99]:
w[1 , 0] = 2
w

array([[1, 2, 3],
       [2, 2, 3]])

In [100]:
w.T

array([[1, 2],
       [2, 2],
       [3, 3]])

In [101]:
m

array([[1, 2, 3],
       [2, 2, 3],
       [3, 4, 5]])

In [103]:
sum(np.diag(m))

8

In [104]:
np.trace(m)   # 1 + 2 + 5 = 8 

8

In [105]:
w = np.array([[1,2,3] , [3,4,7] , [2,5,7]])
w

array([[1, 2, 3],
       [3, 4, 7],
       [2, 5, 7]])

In [106]:
3 - 1 

2

In [107]:
np.linalg.matrix_rank(w)

2

In [108]:
m = np.array([[2,3] , [4,5]])
m

array([[2, 3],
       [4, 5]])

In [111]:
np.linalg.det(m)   # (2 * 5) - (3 * 4) = -2

-2.0

In [113]:
(1/-2) * np.array([[5,-3], [-4 , 2 ]])

array([[-2.5,  1.5],
       [ 2. , -1. ]])

In [116]:
inverse = np.linalg.inv(m)
inverse

array([[-2.5,  1.5],
       [ 2. , -1. ]])

In [117]:
m.dot(inverse)

array([[1., 0.],
       [0., 1.]])

In [118]:
w 

array([[1, 2, 3],
       [3, 4, 7],
       [2, 5, 7]])

In [120]:
# transpose 
# rank

# rows == colsssssss

#     det
#     inv


def stats(data):
    print("transpose: ", w.T)
    print("")
stats(w)

transpose:  [[1 3 2]
 [2 4 5]
 [3 7 7]]



In [121]:
print("amit")

amit


In [122]:
len("amit")

4

In [138]:
def fun_name():
    return "welcome" , "hi"

In [142]:
x , y = fun_name()

In [143]:
fun_name()

('welcome', 'hi')

In [144]:
x

'welcome'

In [145]:
y

'hi'

In [146]:
def add(n1 ,n2 ):
    return n1 + n2

In [149]:
add(12,12)

24

In [150]:
x = add(12,12)

In [151]:
x

24

In [156]:
def stats(data):
    print("Transpose: \n",data.T)
    print("Det: ", np.linalg.det(data))
    print("Inv: " , np.linalg.inv(data))
    print("Rank: ",np.linalg.matrix_rank(data))

In [157]:
stats(w)

Transpose: 
 [[1 3 2]
 [2 4 5]
 [3 7 7]]
Det:  -4.255854927729772e-16
Inv:  [[ 1.64479291e+16 -2.34970415e+15 -4.69940831e+15]
 [ 1.64479291e+16 -2.34970415e+15 -4.69940831e+15]
 [-1.64479291e+16  2.34970415e+15  4.69940831e+15]]
Rank:  2


In [159]:
stats(m)

Transpose: 
 [[2 4]
 [3 5]]
Det:  -2.0
Inv:  [[-2.5  1.5]
 [ 2.  -1. ]]
Rank:  2


In [164]:
m = np.array([[0,0,1,1,0,1,0] , [1,1,0,0,0,1,0]])

In [165]:
m

array([[0, 0, 1, 1, 0, 1, 0],
       [1, 1, 0, 0, 0, 1, 0]])

In [166]:
m.size

14

In [167]:
np.count_nonzero(m) 

6

In [171]:
int((1- (np.count_nonzero(m) / m.size)  ) * 100)

57

In [172]:
from scipy.sparse import csr_matrix , csc_matrix

In [174]:
print(csr_matrix(m)) # row by row 

  (0, 2)	1
  (0, 3)	1
  (0, 5)	1
  (1, 0)	1
  (1, 1)	1
  (1, 5)	1


In [176]:
print(csc_matrix(m))

  (1, 0)	1
  (1, 1)	1
  (0, 2)	1
  (0, 3)	1
  (0, 5)	1
  (1, 5)	1


In [177]:
s = csc_matrix(m)

In [178]:
s.todense()

matrix([[0, 0, 1, 1, 0, 1, 0],
        [1, 1, 0, 0, 0, 1, 0]], dtype=int32)