In [1]:
import numpy as np 

In [2]:
m = np.array([[1,2,3] , [3,4,5] , [5,6,7] , [7,8,9]])
m

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7],
       [7, 8, 9]])

In [3]:
np.mean(m)

5.0

In [4]:
np.mean(m , axis=0)

array([4., 5., 6.])

In [5]:
np.mean(m , axis=1)

array([2., 4., 6., 8.])

In [6]:
np.median(m)

5.0

In [7]:
np.median(m , axis=0)   # col

array([4., 5., 6.])

In [8]:
np.median(m , axis=1)  # row

array([2., 4., 6., 8.])

In [9]:
x = np.array([1,2,3,4,5])
np.var(x)

2.0

In [10]:
np.std(x)

1.4142135623730951

In [16]:
x1 = np.array([1,2,3,4,5,6,7,8,9])
x2 = np.array([1,2,3,4,5,6,7,8,9])
y = np.array([9,8,9,6,7,4,3,2,1])
np.cov(x1,x2)[0 , 1]

7.5

In [18]:
np.corrcoef(x1 , y)

array([[ 1.        , -0.95904144],
       [-0.95904144,  1.        ]])